apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: residencial-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/thiagoholder/residencial-api-config.git
    targetRevision: HEAD
    path: residencial-api
  destination: 
    server: https://kubernetes.default.svc
    namespace: residencial-api

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true