apiVersion: apps/v1
kind: Deployment
metadata:
  name: residencial-api
spec:
  selector:
    matchLabels:
      app: residencial-api
  replicas: 2
  template:
    metadata:
      labels:
        app: residencial-api
    spec:
      containers:
        - name: residencial-api
          image: thiagoholder/residentloan:latest
          ports:
            - containerPort: 80
