apiVersion: apps/v1
kind: Deployment
metadata:
  name: residencial-api
spec:
  selector:
    matchLabels:
      app: residencial-api
  replicas: 2
  template:
    metadata:
      labels:
        app: residencial-api
    spec:
      containers:
        - name: residencial-api
          image: tomorrow.azurecr.io/residentloan:03ec26858c494c273db21835d6f5d213ce5e6985
          ports:
            - containerPort: 5656
      imagePullSecrets:
        - name: acr-secrets
