apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: residencial-api
          image: thiagoholder/residentloan:latest
          ports:
            - containerPort: 80
